/* Generated by AN DISI Unibo */ 
package it.unibo.client

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Client ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("client   |||   init")
					}
					 transition( edgeName="goto",targetState="req", cond=doswitch() )
				}	 
				state("req") { //this:State
					action { //it:State
						delay(2000) 
						request("enter", "enter(idclient)" ,"waiter" )  
						delay(5000) 
						forward("ready", "ready(ready)" ,"waiter" ) 
						delay(5000) 
						forward("ready", "ready(ready)" ,"waiter" ) 
						delay(5000) 
					}
				}	 
			}
		}
}
