/* Generated by AN DISI Unibo */ 
package it.unibo.waitermind

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Waitermind ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
		//	//Coordinates of the entrance door
			val X_EntranceDoor = "0"
			val Y_EntranceDoor = "4"
		
		//	//Coordinates of the exit door
			val X_ExitDoor = "6"
			val Y_ExitDoor = "4"
			
		//  //Coordinates of the barman
			val X_servicedesk = "6"
			val Y_servicedesk = "0"	
		
		//	//Coordinates Tables
			val X_teatable1     = "2"
			val Y_teatable1     = "3"
		
			val X_teatable2     = "5"
			val Y_teatable2     = "3"
		
			//Coordinates of the home
		    val X_home			= "0"
			val Y_home 			= "0"
		
			//Time for serving a client
		//	val servicetime = 1000L 
		
		
			val	Cleantime = 2000L
			val Servicetime = 5000L
			val CollectTime = 4000L
			data class Table(var state: String ="cleaned") {
				
			}
			val table1 = Table()
			val table2 = Table()
			var stateTable1 = "cleaned"
			var stateTable2 = "cleaned"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = false
						println("waiter   |||   init")
					}
					 transition( edgeName="goto",targetState="reachhome", cond=doswitch() )
				}	 
				state("reachhome") { //this:State
					action { //it:State
						println("waiter   |||   reachhome")
						request("moveto", "moveto($X_home,$Y_home)" ,"waiterengine" )  
					}
					 transition(edgeName="t00",targetState="home",cond=whenReply("done"))
				}	 
				state("home") { //this:State
					action { //it:State
						println("waiter   |||   home")
						updateResourceRep( "home"  
						)
					}
					 transition(edgeName="t01",targetState="accept",cond=whenRequest("enter"))
					transition(edgeName="t02",targetState="take",cond=whenDispatch("clientready"))
					transition(edgeName="t03",targetState="reachBarman",cond=whenDispatch("drinkready"))
					transition(edgeName="t04",targetState="reachTableCollect",cond=whenDispatch("paymentready"))
					transition(edgeName="t05",targetState="endwork",cond=whenDispatch("end"))
				}	 
				state("accept") { //this:State
					action { //it:State
						println("waiter   |||   accept")
						answer("enter", "accept", "accept(idclient)"   )  
					}
					 transition( edgeName="goto",targetState="reachEntranceDoor", cond=doswitch() )
				}	 
				state("reachEntranceDoor") { //this:State
					action { //it:State
						println("waiter   |||   reachEntranceDoor")
						updateResourceRep( "reachEntranceDoor"  
						)
						request("moveto", "moveto($X_entrancedoor,$Y_entrancedoor)" ,"waiterengine" )  
					}
					 transition(edgeName="t06",targetState="convoyToTable",cond=whenReply("done"))
				}	 
				state("convoyToTable") { //this:State
					action { //it:State
						println("waiter   |||   convoyToTable")
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
						 table1.state= "occupied"  
						println("waiter   |||   table state occupied")
						updateResourceRep( "convoyToTable"  
						)
					}
					 transition(edgeName="t07",targetState="reachhome",cond=whenReply("done"))
				}	 
				state("take") { //this:State
					action { //it:State
						println("waiter   |||   take")
						updateResourceRep( "take"  
						)
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
					}
					 transition(edgeName="t08",targetState="transmit",cond=whenReply("done"))
				}	 
				state("transmit") { //this:State
					action { //it:State
						println("waiter   |||   transmit")
						updateResourceRep( "transmit"  
						)
					}
					 transition( edgeName="goto",targetState="reachhome", cond=doswitch() )
				}	 
				state("reachBarman") { //this:State
					action { //it:State
						println("waiter   |||   reachBarman")
						updateResourceRep( "reachBarman"  
						)
						request("moveto", "moveto($X_servicedesk,$Y_servicedesk)" ,"waiterengine" )  
					}
					 transition(edgeName="t09",targetState="serve",cond=whenReply("done"))
				}	 
				state("serve") { //this:State
					action { //it:State
						println("waiter   |||   serve")
						updateResourceRep( "serve"  
						)
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
					}
					 transition(edgeName="t010",targetState="reachhome",cond=whenReply("done"))
				}	 
				state("reachTableCollect") { //this:State
					action { //it:State
						println("waiter   |||   reachTable")
						updateResourceRep( "reachTable"  
						)
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
					}
					 transition(edgeName="t011",targetState="collect",cond=whenReply("done"))
				}	 
				state("reachTableClean") { //this:State
					action { //it:State
						println("waiter   |||   reachTable")
						updateResourceRep( "reachTable"  
						)
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
					}
					 transition(edgeName="t012",targetState="clean",cond=whenReply("done"))
				}	 
				state("collect") { //this:State
					action { //it:State
						println("waiter   |||   collect")
						updateResourceRep( "collect"  
						)
						delay(CollectTime)
					}
					 transition( edgeName="goto",targetState="convoyToExitDoor", cond=doswitch() )
				}	 
				state("convoyToExitDoor") { //this:State
					action { //it:State
						println("waiter   |||   convoyToExitDoor")
						updateResourceRep( "convoyToExitDoor"  
						)
						request("moveto", "moveto($X_exitdoor,$Y_exitdoor)" ,"waiterengine" )  
						 table1.state = "dirty"  
						println("waiter   |||   table state dirty")
						delay(5000) 
					}
					 transition(edgeName="t013",targetState="reachTableClean",cond=whenReply("done"))
				}	 
				state("clean") { //this:State
					action { //it:State
						println("waiter   |||   clean")
						updateResourceRep( "clean1"  
						)
						delay(Cleantime)
						 table1.state = "undirty"  
						println("waiter   |||   table state undirty")
					}
					 transition( edgeName="goto",targetState="clean2", cond=doswitch() )
				}	 
				state("clean2") { //this:State
					action { //it:State
						println("waiter   |||   clean2")
						updateResourceRep( "clean2"  
						)
						delay(Cleantime)
						 table1.state = "sanitized"  
						println("waiter   |||   table state sanitized")
					}
					 transition( edgeName="goto",targetState="clean3", cond=doswitch() )
				}	 
				state("clean3") { //this:State
					action { //it:State
						println("waiter   |||   clean3")
						updateResourceRep( "clean3"  
						)
						delay(Cleantime)
						 table1.state = "cleaned"  
						println("waiter   |||   table state cleaned")
					}
					 transition( edgeName="goto",targetState="reachhome", cond=doswitch() )
				}	 
				state("endwork") { //this:State
					action { //it:State
						println("waiter   |||   end")
						terminate(0)
					}
				}	 
			}
		}
}
