/* Generated by AN DISI Unibo */ 
package it.unibo.tearoomstate

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Tearoomstate ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
			var TearoomState = ""
			var E = ""
			var Table = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("tearoomstate START")
						solve("consult('tearoomkb.pl')","") //set resVar	
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						solve("roomstate(S,V,D)","") //set resVar	
						if( currentSolution.isSuccess() ) { TearoomState = getCurSol("S").toString() + "\n" + getCurSol("V").toString() + "\n" + getCurSol("D").toString()  
						}
						else
						{}
						println("tearoomstate s0: $TearoomState")
						updateResourceRep( TearoomState  
						)
					}
					 transition(edgeName="t061",targetState="engageTable",cond=whenDispatch("occupy"))
					transition(edgeName="t062",targetState="cleanTable",cond=whenDispatch("clean"))
					transition(edgeName="t063",targetState="getTable",cond=whenRequest("getTable"))
					transition(edgeName="t064",targetState="tableClean",cond=whenRequest("tableClean"))
					transition(edgeName="t065",targetState="release",cond=whenDispatch("release"))
					transition(edgeName="t066",targetState="replyClean",cond=whenRequest("isClean"))
					transition(edgeName="t067",targetState="setState",cond=whenDispatch("setTableState"))
					transition(edgeName="t068",targetState="tableState",cond=whenRequest("tableState"))
					transition(edgeName="t069",targetState="barmanState",cond=whenDispatch("setBarmanState"))
					transition(edgeName="t070",targetState="waiterState",cond=whenDispatch("setWaiterState"))
				}	 
				state("barmanState") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("setBarmanState(S)"), Term.createTerm("setBarmanState(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 E = payloadArg(0).toString()  
								solve("setBarman($E)","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("waiterState") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("setWaiterState(S)"), Term.createTerm("setWaiterState(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 E = payloadArg(0).toString()  
								println("setWaiterState: $E")
								solve("setWaiter($E)","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("getTable") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("getTable(ID)"), Term.createTerm("getTable(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("getState(N,occupy(${payloadArg(0)}))","") //set resVar	
								if( currentSolution.isSuccess() ) { Table = getCurSol("N").toString().toInt()  
								answer("getTable", "tableId", "tableId($Table)"   )  
								}
								else
								{}
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("tableClean") { //this:State
					action { //it:State
						solve("tableclean(N)","") //set resVar	
						if( currentSolution.isSuccess() ) { Table = getCurSol("N").toString().toInt()  
						answer("tableClean", "table", "table($Table)"   )  
						}
						else
						{answer("tableClean", "table", "table(0)"   )  
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("release") { //this:State
					action { //it:State
						println("tearoomstate   |||   release")
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("release(N)"), Term.createTerm("release(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("releaseTable(${payloadArg(0)})","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("tableState") { //this:State
					action { //it:State
						println("teateables   |||   tableState")
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("tableState(N)"), Term.createTerm("tableState(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Table = payloadArg(0).toString().toInt()  
								solve("getState($Table,S)","") //set resVar	
								if( currentSolution.isSuccess() ) { E = getCurSol("S").toString()  
								}
								else
								{}
								answer("tableState", "state", "state($Table,$E)"   )  
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("setState") { //this:State
					action { //it:State
						println("tearoomstate   |||   setState")
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("setTableState(N,S)"), Term.createTerm("setTableState(N,S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("setState(${payloadArg(0)},${payloadArg(1)})","") //set resVar	
								if( currentSolution.isSuccess() ) {solve("getState(${payloadArg(0)},S)","") //set resVar	
								if( currentSolution.isSuccess() ) {
														println(getCurSol("S").toString())
								}
								else
								{}
								}
								else
								{}
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("replyClean") { //this:State
					action { //it:State
						println("tearoomstate   |||   replyClean")
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("isClean(N)"), Term.createTerm("isClean(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Table = payloadArg(0).toString().toInt()  
								println("onMsg isClean")
								solve("getState($Table,S)","") //set resVar	
								if( currentSolution.isSuccess() ) { 
													E = getCurSol("S").toString()
													if(E == "clean")
														E = "yes"
													else
														E = "no"
								}
								else
								{}
								answer("isClean", "isCleanDone", "isCleanDone($Table,$E)"   )  
								println("replyTo isClean $E")
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("engageTable") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("occupy(N,ID)"), Term.createTerm("occupy(N,ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("engageTable ${payloadArg(0)}, ${payloadArg(1)}")
								solve("occupyTable(${payloadArg(0)},${payloadArg(1)})","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("cleanTable") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("clean(N)"), Term.createTerm("clean(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("clean ${payloadArg(0)}")
								solve("cleanTable(${payloadArg(0)})","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
