/* Generated by AN DISI Unibo */ 
package it.unibo.waitermind

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Waitermind ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
		//	//Coordinates of the entrance door
			val X_Entrancedoor = "0"
			val Y_Entrancedoor = "4"
		
		//	//Coordinates of the exit door
			val X_Exitdoor = "6"
			val Y_Exitdoor = "4"
			
		//  //Coordinates of the barman
			val X_servicedesk = "6"
			val Y_servicedesk = "0"	
		
		//	//Coordinates Tables
			val X_teatable1     = "2"
			val Y_teatable1     = "2"
		
			val X_teatable2     = "4"
			val Y_teatable2     = "2"
		
			//Coordinates of the home
		    val X_home			= "0"
			val Y_home 			= "0"
		
			val	Cleantime = 3000L
			val Servicetime = 5000L
			val CollectTime = 4000L
			data class Table(var state: String ="cleaned") {
				
			}
			val table1 = Table()
			val table2 = Table()
			var stateTable1 = "cleaned"
			var stateTable2 = "cleaned"
			
			var isCleanStopped = false
			var tableStopped = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = false
						println("waitermind   |||   init")
						request("start", "start(id)" ,"waiterengine" )  
					}
					 transition(edgeName="t00",targetState="home",cond=whenReply("ready"))
				}	 
				state("reachhome") { //this:State
					action { //it:State
						println("waitermind   |||   reachhome")
						request("moveto", "moveto($X_home,$Y_home)" ,"waiterengine" )  
					}
					 transition(edgeName="t01",targetState="home",cond=whenReply("done"))
				}	 
				state("home") { //this:State
					action { //it:State
						println("waitermind   |||   home")
						updateResourceRep( "home"  
						)
					}
					 transition(edgeName="t02",targetState="accept",cond=whenRequest("enter"))
					transition(edgeName="t03",targetState="take",cond=whenDispatch("clientready"))
					transition(edgeName="t04",targetState="reachBarman",cond=whenDispatch("drinkready"))
					transition(edgeName="t05",targetState="reachTableCollect",cond=whenDispatch("paymentready"))
					transition(edgeName="t06",targetState="endwork",cond=whenDispatch("end"))
				}	 
				state("accept") { //this:State
					action { //it:State
						println("waitermind   |||   accept")
						answer("enter", "accept", "accept(idclient)"   )  
					}
					 transition( edgeName="goto",targetState="reachEntranceDoor", cond=doswitch() )
				}	 
				state("reachEntranceDoor") { //this:State
					action { //it:State
						println("waitermind   |||   reachEntranceDoor")
						request("moveto", "moveto($X_Entrancedoor,$Y_Entrancedoor)" ,"waiterengine" )  
					}
					 transition(edgeName="t07",targetState="checkTables",cond=whenReply("done"))
				}	 
				state("checkTables") { //this:State
					action { //it:State
						println("waitermind   |||   checkTables")
					}
					 transition( edgeName="goto",targetState="convoyToTable1", cond=doswitchGuarded({ table1.state=="cleaned"  
					}) )
					transition( edgeName="goto",targetState="convoyToTable2", cond=doswitchGuarded({! ( table1.state=="cleaned"  
					) }) )
				}	 
				state("convoyToTable1") { //this:State
					action { //it:State
						println("waitermind   |||   convoyToTable1")
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
						 table1.state= "occupied"  
						println("waitermind   |||   table1 state occupied")
						delay(5000) 
					}
					 transition(edgeName="t08",targetState="checkCleanHome",cond=whenReply("done"))
				}	 
				state("convoyToTable2") { //this:State
					action { //it:State
						println("waitermind   |||   convoyToTable2")
						request("moveto", "moveto($X_teatable2,$Y_teatable2)" ,"waiterengine" )  
						 table2.state= "occupied"  
						println("waitermind   |||   table2 state occupied")
						delay(5000) 
					}
					 transition(edgeName="t09",targetState="checkCleanHome",cond=whenReply("done"))
				}	 
				state("checkCleanHome") { //this:State
					action { //it:State
						println("waitermind   |||   checkClean")
					}
					 transition( edgeName="goto",targetState="reachhome", cond=doswitchGuarded({ !isCleanStopped  
					}) )
					transition( edgeName="goto",targetState="reachTable1CleanStopped", cond=doswitchGuarded({! ( !isCleanStopped  
					) }) )
				}	 
				state("reachTable1CleanStopped") { //this:State
					action { //it:State
						println("waitermind   |||   reachTable1CleanStopped")
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
					}
					 transition(edgeName="t010",targetState="checkCleanStopped",cond=whenReply("done"))
				}	 
				state("checkCleanStopped") { //this:State
					action { //it:State
						println("waitermind   |||   checkCleanStopped")
						if(  tableStopped=="table1"  
						 ){if(  table1.state == "dirty"  
						 ){forward("gotoclean", "gotoclean(clean1)" ,"waitermind" ) 
						}
						else
						 {if(  table1.state == "undirty"  
						  ){forward("gotoclean2", "gotoclean2(clean2)" ,"waitermind" ) 
						 }
						 else
						  {forward("gotoclean3", "gotoclean3(clean3)" ,"waitermind" ) 
						  }
						 }
						}
						else
						 {if(  table2.state == "dirty"  
						  ){forward("gotoclean", "gotoclean(clean1)" ,"waitermind" ) 
						 }
						 else
						  {if(  table2.state == "undirty"  
						   ){forward("gotoclean2", "gotoclean2(clean2)" ,"waitermind" ) 
						  }
						  else
						   {forward("gotoclean3", "gotoclean3(clean3)" ,"waitermind" ) 
						   }
						  }
						 }
					}
					 transition(edgeName="t011",targetState="clean",cond=whenDispatch("gotoclean"))
					transition(edgeName="t012",targetState="clean2",cond=whenDispatch("gotoclean2"))
					transition(edgeName="t013",targetState="clean3",cond=whenDispatch("gotoclean3"))
				}	 
				state("take") { //this:State
					action { //it:State
						println("waitermind   |||   take")
						updateResourceRep( "take"  
						)
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
					}
					 transition(edgeName="t014",targetState="transmit",cond=whenReply("done"))
				}	 
				state("transmit") { //this:State
					action { //it:State
						println("waitermind   |||   transmit")
						updateResourceRep( "transmit"  
						)
					}
					 transition( edgeName="goto",targetState="reachhome", cond=doswitch() )
				}	 
				state("reachBarman") { //this:State
					action { //it:State
						println("waitermind   |||   reachBarman")
						updateResourceRep( "reachBarman"  
						)
						request("moveto", "moveto($X_servicedesk,$Y_servicedesk)" ,"waiterengine" )  
					}
					 transition(edgeName="t015",targetState="serve",cond=whenReply("done"))
				}	 
				state("serve") { //this:State
					action { //it:State
						println("waitermind   |||   serve")
						updateResourceRep( "serve"  
						)
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
					}
					 transition(edgeName="t016",targetState="reachhome",cond=whenReply("done"))
				}	 
				state("reachTableCollect") { //this:State
					action { //it:State
						println("waitermind   |||   reachTable")
						updateResourceRep( "reachTable"  
						)
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
					}
					 transition(edgeName="t017",targetState="collect",cond=whenReply("done"))
				}	 
				state("reachTableClean") { //this:State
					action { //it:State
						println("waitermind   |||   reachTable")
						updateResourceRep( "reachTable"  
						)
						request("moveto", "moveto($X_teatable1,$Y_teatable1)" ,"waiterengine" )  
					}
					 transition(edgeName="t018",targetState="clean",cond=whenReply("done"))
				}	 
				state("collect") { //this:State
					action { //it:State
						println("waitermind   |||   collect")
						updateResourceRep( "collect"  
						)
						delay(CollectTime)
					}
					 transition( edgeName="goto",targetState="convoyToExitDoor", cond=doswitch() )
				}	 
				state("convoyToExitDoor") { //this:State
					action { //it:State
						println("waitermind   |||   convoyToExitDoor")
						updateResourceRep( "convoyToExitDoor"  
						)
						request("moveto", "moveto($X_Exitdoor,$Y_Exitdoor)" ,"waiterengine" )  
						 table1.state = "dirty"  
						println("waitermind   |||   table state dirty")
						delay(5000) 
					}
					 transition(edgeName="t019",targetState="reachTableClean",cond=whenReply("done"))
				}	 
				state("stopCleanEnter") { //this:State
					action { //it:State
						updateResourceRep( "cleanStopped"  
						)
						 
									isCleanStopped = true
									tableStopped = "table1"	
					}
					 transition( edgeName="goto",targetState="accept", cond=doswitch() )
				}	 
				state("clean") { //this:State
					action { //it:State
						println("waitermind   |||   clean")
						stateTimer = TimerActor("timer_clean", 
							scope, context!!, "local_tout_waitermind_clean", Cleantime )
					}
					 transition(edgeName="t020",targetState="clean2",cond=whenTimeout("local_tout_waitermind_clean"))   
					transition(edgeName="t021",targetState="stopCleanEnter",cond=whenRequest("enter"))
				}	 
				state("clean2") { //this:State
					action { //it:State
						println("waitermind   |||   clean2")
						 table1.state = "undirty"  
						stateTimer = TimerActor("timer_clean2", 
							scope, context!!, "local_tout_waitermind_clean2", Cleantime )
					}
					 transition(edgeName="t022",targetState="clean3",cond=whenTimeout("local_tout_waitermind_clean2"))   
					transition(edgeName="t023",targetState="stopCleanEnter",cond=whenRequest("enter"))
				}	 
				state("clean3") { //this:State
					action { //it:State
						println("waitermind   |||   clean3")
						 table1.state = "sanitized"  
						stateTimer = TimerActor("timer_clean3", 
							scope, context!!, "local_tout_waitermind_clean3", Cleantime )
					}
					 transition(edgeName="t024",targetState="clean4",cond=whenTimeout("local_tout_waitermind_clean3"))   
					transition(edgeName="t025",targetState="stopCleanEnter",cond=whenRequest("enter"))
				}	 
				state("clean4") { //this:State
					action { //it:State
						 table1.state = "cleaned"  
					}
					 transition( edgeName="goto",targetState="reachhome", cond=doswitch() )
				}	 
				state("endwork") { //this:State
					action { //it:State
						println("waitermind   |||   end")
						terminate(0)
					}
				}	 
			}
		}
}
