/* Generated by AN DISI Unibo */ 
package it.unibo.staytimertable1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Staytimertable1 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				val MaxStayTime = 60*10L //In secondi
				var TimePassed = 0L
				var RemTime = 0L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = true
						println("staytimertable1   |||   init")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("getRemainingTime(N)"), Term.createTerm("getRemainingTime(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RemTime = MaxStayTime - TimePassed  
								answer("getRemainingTime", "remainingTime", "remainingTime($RemTime)"   )  
						}
						println("staytimertable1   |||   wait")
					}
					 transition(edgeName="t094",targetState="start",cond=whenDispatch("starttimer"))
					transition(edgeName="t095",targetState="wait",cond=whenRequest("getRemainingTime"))
				}	 
				state("start") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("starttimer(T)"), Term.createTerm("starttimer(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("staytimertable1   |||   start")
						}
						 TimePassed++  
						if(  TimePassed>=MaxStayTime  
						 ){forward("endtime", "endtime($TimePassed)" ,"staytimertable1" ) 
						}
						stateTimer = TimerActor("timer_start", 
							scope, context!!, "local_tout_staytimertable1_start", 1000.toLong() )
					}
					 transition(edgeName="t096",targetState="start",cond=whenTimeout("local_tout_staytimertable1_start"))   
					transition(edgeName="t097",targetState="replyTimeStart",cond=whenRequest("getRemainingTime"))
					transition(edgeName="t098",targetState="wait",cond=whenDispatch("stopstaytimer"))
					transition(edgeName="t099",targetState="timeFinish",cond=whenDispatch("endtime"))
					transition(edgeName="t0100",targetState="end",cond=whenDispatch("timeroff"))
				}	 
				state("replyTimeStart") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("getRemainingTime(N)"), Term.createTerm("getRemainingTime(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RemTime = MaxStayTime - TimePassed  
								answer("getRemainingTime", "remainingTime", "remainingTime($RemTime)"   )  
						}
					}
					 transition( edgeName="goto",targetState="start", cond=doswitch() )
				}	 
				state("end") { //this:State
					action { //it:State
						 RemTime = 0L  
						 TimePassed = 0L  
						println("staytimertable1   |||   ended")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("timeFinish") { //this:State
					action { //it:State
						 RemTime = 0L  
						 TimePassed = 0L  
						println("maxstaytimer   |||   timeFinish")
						forward("timePassed", "timePassed(1)" ,"maxstaytimer" ) 
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
