/* Generated by AN DISI Unibo */ 
package it.unibo.staytimertable1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Staytimertable1 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				val MaxStayTime = 60*10L //In secondi
				var TimePassed = 0L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("staytimertable1   |||   init")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("staytimertable1   |||   wait")
					}
					 transition(edgeName="t076",targetState="start",cond=whenDispatch("starttimer"))
				}	 
				state("start") { //this:State
					action { //it:State
						println("staytimertable1   |||   start")
						println("$name in ${currentState.stateName} | $currentMsg")
						 TimePassed++  
						if(  TimePassed>=MaxStayTime  
						 ){forward("endtime", "endtime($TimePassed)" ,"staytimertable1" ) 
						}
						stateTimer = TimerActor("timer_start", 
							scope, context!!, "local_tout_staytimertable1_start", 1000.toLong() )
					}
					 transition(edgeName="t077",targetState="start",cond=whenTimeout("local_tout_staytimertable1_start"))   
					transition(edgeName="t078",targetState="wait",cond=whenDispatch("stopstaytimer"))
					transition(edgeName="t079",targetState="timeFinish",cond=whenDispatch("endtime"))
					transition(edgeName="t080",targetState="end",cond=whenDispatch("timeroff"))
				}	 
				state("end") { //this:State
					action { //it:State
						 TimePassed = 0L  
						println("staytimertable1   |||   ended")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("timeFinish") { //this:State
					action { //it:State
						 TimePassed = 0L  
						println("maxstaytimer   |||   timeFinish")
						forward("timePassed", "timePassed(1)" ,"maxstaytimer" ) 
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
